language: node_js
node_js:
- 9.10.1
install:
- npm i
cache:
  directories:
  - node_modules
script: npm run build:extension -env.FIREBASE_KEY $FIREBASE_KEY
env:
  global:
    secure: cTLkVbTqf5ruNqRA1vUHdLqv9SczrsxPjIlO5Ri4n1V5vacvC8BN3meNkuX5FrCLnucxTMHo4liG3Oor4On0rRmSBpoK0fu/a6prmLya2Tfc9YEeM+Lfr1yw+9APGh2nYEMbPgI+rbHMA1Q7b/krH7lpjiJZWNensesemHfIBqD1qKbNTrjgTHebEDMViroO6tQBLQ+NTJg9q/8ZgqTwLykRt9QUQkFuFoopP9Bl0BGNs1X4QcUlvOs2BjyUyxOaYuMx6OMn3L+RAPQ7TLChG7tAna5YGWu9PwRmUuIngT7hhFm7urSXYH3Ab3JgncG9HZAUk7RiB4tr9wwlv0BGnmamZBQG/EwtIdghrOPi58bzwPGguKpPA2ppeBbG0y6z1FXv/IDYYX7hAletBTzwZFKzQ+fqPqQ0gmvnaDruLkp7aJCJcHMBjfBagyzqKzkIoCwXIXTfUY7DzcqrvxYIavpjR8DpWUi8RCTrifS/uFUBqAnkRB0LDMenudYR+ottNCHNNa4kp33vcVTlJrHd4tKZh2RZJcV778KgOFM0TKZJbc19xeJI3VkWYXnircypGVpTxUZvFrbsPfw51nfNWX7sYOpZoHgrcd3UrjB4KUT7ra1uRAbZPdfNtVAtvCR7C9bU+czWXOaiSC0gz6PFqknNhX8c07zQX57RqHnRlaU=
dd:
  secure: FoCehbCgz3IYqkstAOrwa2V3p4CEEmfYSLy4OxQJjlcWzHUs8NBgy1rmYoi7Jk4F259FyAV0GPOC/TkEyERAgWAL68CYnhgfF8QZ8z5l5PHQlzXE8/nAjX9Lej5frsV1iQBhJrOkNzZaG7kcwBSh+xdgoavhRxHFv7b1Ko0+rDkAOI9J8KGM9evRLIY1b7XbzKkmzpmddg+enj8Pw1aAN53uo2UzasrsTNc0VdDX3wukQiqqAnddzrtDXO+Zww3IXAg/RM173ygPXw7e7FvyZJ92/VDMQsDc3Bov8aVlHr5Unvu5Qbe45EnjXMZuqpW6KMPBpeGK5LDWr1vSf/rMdQFFqd/q77FdFi/Z6yLwzYVm6+UkCe2JtAM4I5TRMqNd8w8rLPmG+UY97VYhmbsYDYVw5T3g4pJH0EOiSdtSv2aNUBqqDdQH9WCDBa9WEtOGwkLKqtIncmykYXaCBR+DQytFQ4MvTKkbR072UyluUZU4YVp/caU0ixFpr/YLVau/YB7TLtksQy0CfhK35GkpQs8ySmjiiqv05EBQMaZuUX+GLotuRZjFXsE69DHg9U3OE4/gph9MdFK4qZXXFZMLlpwt0GQ6ZjUNOcxWKKbssAiMYBwqII+V7Wf9MIBucv004ujn7WDQu+UmTi+64qJMwNRO5FJTO0QMi8vv5Pfc57E=
